package kira.mkxthreat.scripts.world.systems;

import com.fs.starfarer.api.Global;
import com.fs.starfarer.api.campaign.*;
import com.fs.starfarer.api.campaign.econ.MarketAPI;
import com.fs.starfarer.api.impl.campaign.ids.*;
import com.fs.starfarer.api.impl.campaign.intel.deciv.DecivTracker;
import com.fs.starfarer.api.impl.campaign.procgen.NebulaEditor;
import com.fs.starfarer.api.impl.campaign.terrain.HyperspaceAbyssPluginImpl;
import com.fs.starfarer.api.impl.campaign.terrain.HyperspaceTerrainPlugin;
import com.fs.starfarer.api.util.Misc;
import kira.mkxthreat.campaign.econ.MkxthreatHabitatCondition;
import kira.mkxthreat.campaign.econ.industries.MkxIndustries;
import kira.mkxthreat.campaign.submarkets.Mkxthreathab;

import java.awt.*;
import java.util.ArrayList;
import java.util.Arrays;

public class Helia {

    public static void setAbyssalDetectedRanges(StarSystemAPI system) {   //Needed to get the star to not show on the map//
        if (system.getAutogeneratedJumpPointsInHyper() != null) {
            for (JumpPointAPI jp : system.getAutogeneratedJumpPointsInHyper()) {
                if (jp.isStarAnchor()) {
                    jp.addTag(Tags.STAR_HIDDEN_ON_MAP);
                }
                float range = HyperspaceAbyssPluginImpl.JUMP_POINT_DETECTED_RANGE;
                if (jp.isGasGiantAnchor()) {
                    range = HyperspaceAbyssPluginImpl.GAS_GIANT_DETECTED_RANGE;
                } else if (jp.isStarAnchor()) {
                    range = HyperspaceAbyssPluginImpl.STAR_DETECTED_RANGE;
                }
                setAbyssalDetectedRange(jp, range);
            }
        }

        if (system.getAutogeneratedNascentWellsInHyper() != null) {
            for (NascentGravityWellAPI well : system.getAutogeneratedNascentWellsInHyper()) {
                setAbyssalDetectedRange(well, HyperspaceAbyssPluginImpl.NASCENT_WELL_DETECTED_RANGE);
            }
        }
    }

    public static void setAbyssalDetectedRange(SectorEntityToken entity, float range) {
        float detectedRange = range / HyperspaceTerrainPlugin.ABYSS_SENSOR_RANGE_MULT;

        float maxSensorRange = Global.getSettings().getSensorRangeMaxHyper();
        float desired = detectedRange * HyperspaceTerrainPlugin.ABYSS_SENSOR_RANGE_MULT;
        if (desired > maxSensorRange) {
            entity.setExtendedDetectedAtRange(desired - maxSensorRange);
        }

        entity.setSensorProfile(1f);
        entity.setDiscoverable(false);
        entity.getDetectedRangeMod().modifyFlat("jpDetRange", detectedRange);

        float mult = Math.min(0.5f, 400f / range);
        entity.setDetectionRangeDetailsOverrideMult(mult);
    }   //Needed to get the star to not show on the map//

    public void generate(SectorAPI sector) {

        StarSystemAPI system = sector.createStarSystem("Helia");

        system.getLocation().set(-68300, -42600); //position of the system on the map

        PlanetAPI helia = system.initStar("Helia", "Helia", 1000f, 600);

        helia.setCustomDescriptionId("Helia");

        system.setBackgroundTextureFilename("graphics/backgrounds/background4.jpg");
        system.setLightColor(new Color(130, 155, 145)); // light color in entire system, affects all entities

        system.addAsteroidBelt(helia, 150, 3200, 500, 290, 310, Terrain.ASTEROID_BELT, "Fragmented planet");
        system.addRingBand(helia, "misc", "rings_ice0", 256f, 0, Color.gray, 256f, 3200, 360f, null, null);

        system.autogenerateHyperspaceJumpPoints(true, true); //generates jump points
        setAbyssalDetectedRanges(system); //sets the system to only be detected when close//

        system.setHyperspaceAnchor(helia);
        SectorEntityToken mkxthreatSensorArray = system.addCustomEntity("mkxthreat_sensor", "Domain Sensor Array", "sensor_array", "mkxthreat");
        SectorEntityToken mkxthreatNavArray = system.addCustomEntity("mkxthreat_nav", "Domain Navigation Array", "nav_buoy", "mkxthreat");
        SectorEntityToken mkxthreatRelay = system.addCustomEntity("mkxthreat_relay", "Domain Communication Array", "comm_relay", "mkxthreat");

        mkxthreatSensorArray.setCircularOrbitPointingDown(helia, 240.0F, 3400.0F, 260.0F);
        mkxthreatNavArray.setCircularOrbitPointingDown(helia, 240.0F, 3000.0F, 200.0F);
        mkxthreatRelay.setCircularOrbitPointingDown(helia, 185.0F, 2800.0F, 100.0F);

        HyperspaceTerrainPlugin plugin = (HyperspaceTerrainPlugin) Misc.getHyperspaceTerrain().getPlugin(); //these lines clear the hyperspace clouds around the system

        NebulaEditor editor = new NebulaEditor(plugin);
        float minRadius = plugin.getTileSize() * 2f;

        float radius = system.getMaxRadiusInHyperspace();
        editor.clearArc(system.getLocation().x, system.getLocation().y, 0, radius + minRadius, 0, 360f);
        editor.clearArc(system.getLocation().x, system.getLocation().y, 0, radius + minRadius, 0, 360f, 0.25f);

        PlanetAPI hel = system.addPlanet("Hel", helia, "Hel", "Hel", 900, 180f, 4000, 220f);

        hel.setCustomDescriptionId("Hel");
        hel.setInteractionImage("illustrations", "sentinel");
        hel.getSpec().setGlowTexture(Global.getSettings().getSpriteName("hab_glows", "hel_glow"));
        hel.applySpecChanges();

        system.addRingBand(hel, "misc", "rings_ice0", 300f, 1, Color.gray, 250f, 500, 300f, null, null);
        system.addAsteroidBelt(hel, 20, 280, 55, 100, 150);

        MarketAPI helmarket = AddMarketplace.addMarketplace("mkxthreat", hel, null, "Hel", 8,

                new ArrayList<>(Arrays.asList( //conditions
                        Conditions.ORE_ULTRARICH,
                        Conditions.RARE_ORE_ULTRARICH,
                        Conditions.VOLATILES_PLENTIFUL,
                        Conditions.POPULATION_8,
                        Conditions.STEALTH_MINEFIELDS,
                        MkxthreatHabitatCondition.MKXTHREATHABITATCONDITION,
                        Conditions.AI_CORE_ADMIN
                )),

                new ArrayList<>(Arrays.asList( //industries
                        MkxIndustries.MKXTHREATFRAGMENTCORE,
                        Industries.MEGAPORT,
                        Industries.WAYSTATION,
                        MkxIndustries.MKXTHREATPLANETARYSHIELD,
                        MkxIndustries.MKXTHREATMINING,
                        MkxIndustries.MKXTHREATMILITARYBASE,
                        MkxIndustries.MKXFRAGMENTSTATION,
                        MkxIndustries.MKXHEAVYBATTERIES
                )),

                new ArrayList<>(Arrays.asList( //markets
                        Submarkets.SUBMARKET_STORAGE,
                        Submarkets.SUBMARKET_OPEN,
                        Mkxthreathab.MKXTHREATHAB,
                        Submarkets.GENERIC_MILITARY
                )),

                0.15f

        );

        helmarket.addIndustry("mkxfragmentworks", new ArrayList(Arrays.asList("mkxthreatfragmenthub")));
        helmarket.getMemoryWithoutUpdate().set(DecivTracker.NO_DECIV_KEY, true);
    }
}
